"""auroraWX installer for WeeWX 5.x.

Install with:  weectl extension install <this-file-or-package>
Remove with:   weectl extension uninstall aurorawx
"""
from weecfg.extension import ExtensionInstaller

VERSION = "1.0.0"

# --- BEGIN GENERATED SKIN FILES (tools/gen_install.py) ---
SKIN_FILES = [
    'skins/aurorawx/almanac.html.tmpl',
    'skins/aurorawx/archive.html.tmpl',
    'skins/aurorawx/archive/NOAA-%Y-%m.txt.tmpl',
    'skins/aurorawx/archive/NOAA-%Y.txt.tmpl',
    'skins/aurorawx/aurora.html.tmpl',
    'skins/aurorawx/css/aurora.css',
    'skins/aurorawx/css/bootstrap.min.css',
    'skins/aurorawx/css/style.css',
    'skins/aurorawx/css/style.min.css',
    'skins/aurorawx/fonts/OFL.txt',
    'skins/aurorawx/fonts/Rubik-Light.eot',
    'skins/aurorawx/fonts/Rubik-Light.woff',
    'skins/aurorawx/fonts/Rubik-Light.woff2',
    'skins/aurorawx/fonts/Rubik-Regular.eot',
    'skins/aurorawx/fonts/Rubik-Regular.woff',
    'skins/aurorawx/fonts/Rubik-Regular.woff2',
    'skins/aurorawx/footer.inc',
    'skins/aurorawx/gallery.html.tmpl',
    'skins/aurorawx/graph_area_archive_config.inc',
    'skins/aurorawx/graph_area_config.inc',
    'skins/aurorawx/graph_bar_archive_config.inc',
    'skins/aurorawx/graph_bar_config.inc',
    'skins/aurorawx/graph_radar_config.inc',
    'skins/aurorawx/head.inc',
    'skins/aurorawx/header.inc',
    'skins/aurorawx/img/icon-120.png',
    'skins/aurorawx/img/icon-128.png',
    'skins/aurorawx/img/icon-144.png',
    'skins/aurorawx/img/icon-152.png',
    'skins/aurorawx/img/icon-16.ico',
    'skins/aurorawx/img/icon-16.png',
    'skins/aurorawx/img/icon-168.png',
    'skins/aurorawx/img/icon-180.png',
    'skins/aurorawx/img/icon-192.png',
    'skins/aurorawx/img/icon-256.png',
    'skins/aurorawx/img/icon-32.png',
    'skins/aurorawx/img/icon-48.png',
    'skins/aurorawx/img/icon-512.png',
    'skins/aurorawx/img/icon-72.png',
    'skins/aurorawx/img/icon-76.png',
    'skins/aurorawx/img/icon-96.png',
    'skins/aurorawx/img/icon-alpha-1x.png',
    'skins/aurorawx/img/icon-alpha-2x.png',
    'skins/aurorawx/img/splash/splash_1125x2436.png',
    'skins/aurorawx/img/splash/splash_1136x640.png',
    'skins/aurorawx/img/splash/splash_1242x2208.png',
    'skins/aurorawx/img/splash/splash_1242x2688.png',
    'skins/aurorawx/img/splash/splash_1334x750.png',
    'skins/aurorawx/img/splash/splash_1536x2048.png',
    'skins/aurorawx/img/splash/splash_1668x2224.png',
    'skins/aurorawx/img/splash/splash_1668x2388.png',
    'skins/aurorawx/img/splash/splash_1792x828.png',
    'skins/aurorawx/img/splash/splash_2048x1536.png',
    'skins/aurorawx/img/splash/splash_2048x2732.png',
    'skins/aurorawx/img/splash/splash_2208x1242.png',
    'skins/aurorawx/img/splash/splash_2224x1668.png',
    'skins/aurorawx/img/splash/splash_2388x1668.png',
    'skins/aurorawx/img/splash/splash_2436x1125.png',
    'skins/aurorawx/img/splash/splash_2688x1242.png',
    'skins/aurorawx/img/splash/splash_2732x2048.png',
    'skins/aurorawx/img/splash/splash_640x1136.png',
    'skins/aurorawx/img/splash/splash_750x1334.png',
    'skins/aurorawx/img/splash/splash_828x1792.png',
    'skins/aurorawx/index.html.tmpl',
    'skins/aurorawx/js.inc',
    'skins/aurorawx/js/app.js',
    'skins/aurorawx/js/bootstrap.js',
    'skins/aurorawx/js/bootstrap.min.js',
    'skins/aurorawx/js/jquery.js',
    'skins/aurorawx/js/jquery.min.js',
    'skins/aurorawx/js/mdb.js',
    'skins/aurorawx/js/mdb.min.js',
    'skins/aurorawx/js/mdb.min.js.map',
    'skins/aurorawx/js/modules/aurora.js',
    'skins/aurorawx/js/modules/wow.min.js',
    'skins/aurorawx/js/popper.js',
    'skins/aurorawx/js/popper.min.js',
    'skins/aurorawx/js/vendor/apexcharts/LICENSE',
    'skins/aurorawx/js/vendor/apexcharts/apexcharts.min.js',
    'skins/aurorawx/js/vendor/apexcharts/locales/ca.json',
    'skins/aurorawx/js/vendor/apexcharts/locales/cs.json',
    'skins/aurorawx/js/vendor/apexcharts/locales/de.json',
    'skins/aurorawx/js/vendor/apexcharts/locales/el.json',
    'skins/aurorawx/js/vendor/apexcharts/locales/en.json',
    'skins/aurorawx/js/vendor/apexcharts/locales/es.json',
    'skins/aurorawx/js/vendor/apexcharts/locales/fi.json',
    'skins/aurorawx/js/vendor/apexcharts/locales/fr.json',
    'skins/aurorawx/js/vendor/apexcharts/locales/he.json',
    'skins/aurorawx/js/vendor/apexcharts/locales/hi.json',
    'skins/aurorawx/js/vendor/apexcharts/locales/hr.json',
    'skins/aurorawx/js/vendor/apexcharts/locales/hy.json',
    'skins/aurorawx/js/vendor/apexcharts/locales/id.json',
    'skins/aurorawx/js/vendor/apexcharts/locales/it.json',
    'skins/aurorawx/js/vendor/apexcharts/locales/ka.json',
    'skins/aurorawx/js/vendor/apexcharts/locales/ko.json',
    'skins/aurorawx/js/vendor/apexcharts/locales/lt.json',
    'skins/aurorawx/js/vendor/apexcharts/locales/nb.json',
    'skins/aurorawx/js/vendor/apexcharts/locales/nl.json',
    'skins/aurorawx/js/vendor/apexcharts/locales/pl.json',
    'skins/aurorawx/js/vendor/apexcharts/locales/pt-br.json',
    'skins/aurorawx/js/vendor/apexcharts/locales/pt.json',
    'skins/aurorawx/js/vendor/apexcharts/locales/rs.json',
    'skins/aurorawx/js/vendor/apexcharts/locales/ru.json',
    'skins/aurorawx/js/vendor/apexcharts/locales/se.json',
    'skins/aurorawx/js/vendor/apexcharts/locales/sk.json',
    'skins/aurorawx/js/vendor/apexcharts/locales/sl.json',
    'skins/aurorawx/js/vendor/apexcharts/locales/sq.json',
    'skins/aurorawx/js/vendor/apexcharts/locales/th.json',
    'skins/aurorawx/js/vendor/apexcharts/locales/tr.json',
    'skins/aurorawx/js/vendor/apexcharts/locales/ua.json',
    'skins/aurorawx/js/vendor/apexcharts/locales/zh-cn.json',
    'skins/aurorawx/js/vendor/moment-with-locales.min.js',
    'skins/aurorawx/js/vendor/moment.min.js',
    'skins/aurorawx/manifest.json',
    'skins/aurorawx/month-%Y-%m.html.tmpl',
    'skins/aurorawx/month.html.tmpl',
    'skins/aurorawx/skin.conf',
    'skins/aurorawx/solar.html.tmpl',
    'skins/aurorawx/telemetry.html.tmpl',
    'skins/aurorawx/weather-icons/README.md',
    'skins/aurorawx/weather-icons/css/weather-icons-wind.css',
    'skins/aurorawx/weather-icons/css/weather-icons-wind.min.css',
    'skins/aurorawx/weather-icons/css/weather-icons.css',
    'skins/aurorawx/weather-icons/css/weather-icons.min.css',
    'skins/aurorawx/weather-icons/font/weathericons-regular-webfont.eot',
    'skins/aurorawx/weather-icons/font/weathericons-regular-webfont.svg',
    'skins/aurorawx/weather-icons/font/weathericons-regular-webfont.ttf',
    'skins/aurorawx/weather-icons/font/weathericons-regular-webfont.woff',
    'skins/aurorawx/weather-icons/font/weathericons-regular-webfont.woff2',
    'skins/aurorawx/weather-icons/svg/wi-alien.svg',
    'skins/aurorawx/weather-icons/svg/wi-barometer.svg',
    'skins/aurorawx/weather-icons/svg/wi-celsius.svg',
    'skins/aurorawx/weather-icons/svg/wi-cloud-down.svg',
    'skins/aurorawx/weather-icons/svg/wi-cloud-refresh.svg',
    'skins/aurorawx/weather-icons/svg/wi-cloud-up.svg',
    'skins/aurorawx/weather-icons/svg/wi-cloud.svg',
    'skins/aurorawx/weather-icons/svg/wi-cloudy-gusts.svg',
    'skins/aurorawx/weather-icons/svg/wi-cloudy-windy.svg',
    'skins/aurorawx/weather-icons/svg/wi-cloudy.svg',
    'skins/aurorawx/weather-icons/svg/wi-day-cloudy-gusts.svg',
    'skins/aurorawx/weather-icons/svg/wi-day-cloudy-high.svg',
    'skins/aurorawx/weather-icons/svg/wi-day-cloudy-windy.svg',
    'skins/aurorawx/weather-icons/svg/wi-day-cloudy.svg',
    'skins/aurorawx/weather-icons/svg/wi-day-fog.svg',
    'skins/aurorawx/weather-icons/svg/wi-day-hail.svg',
    'skins/aurorawx/weather-icons/svg/wi-day-haze.svg',
    'skins/aurorawx/weather-icons/svg/wi-day-light-wind.svg',
    'skins/aurorawx/weather-icons/svg/wi-day-lightning.svg',
    'skins/aurorawx/weather-icons/svg/wi-day-rain-mix.svg',
    'skins/aurorawx/weather-icons/svg/wi-day-rain-wind.svg',
    'skins/aurorawx/weather-icons/svg/wi-day-rain.svg',
    'skins/aurorawx/weather-icons/svg/wi-day-showers.svg',
    'skins/aurorawx/weather-icons/svg/wi-day-sleet-storm.svg',
    'skins/aurorawx/weather-icons/svg/wi-day-sleet.svg',
    'skins/aurorawx/weather-icons/svg/wi-day-snow-thunderstorm.svg',
    'skins/aurorawx/weather-icons/svg/wi-day-snow-wind.svg',
    'skins/aurorawx/weather-icons/svg/wi-day-snow.svg',
    'skins/aurorawx/weather-icons/svg/wi-day-sprinkle.svg',
    'skins/aurorawx/weather-icons/svg/wi-day-storm-showers.svg',
    'skins/aurorawx/weather-icons/svg/wi-day-sunny-overcast.svg',
    'skins/aurorawx/weather-icons/svg/wi-day-sunny.svg',
    'skins/aurorawx/weather-icons/svg/wi-day-thunderstorm.svg',
    'skins/aurorawx/weather-icons/svg/wi-day-windy.svg',
    'skins/aurorawx/weather-icons/svg/wi-degrees.svg',
    'skins/aurorawx/weather-icons/svg/wi-direction-down-left.svg',
    'skins/aurorawx/weather-icons/svg/wi-direction-down-right.svg',
    'skins/aurorawx/weather-icons/svg/wi-direction-down.svg',
    'skins/aurorawx/weather-icons/svg/wi-direction-left.svg',
    'skins/aurorawx/weather-icons/svg/wi-direction-right.svg',
    'skins/aurorawx/weather-icons/svg/wi-direction-up-left.svg',
    'skins/aurorawx/weather-icons/svg/wi-direction-up-right.svg',
    'skins/aurorawx/weather-icons/svg/wi-direction-up.svg',
    'skins/aurorawx/weather-icons/svg/wi-dust.svg',
    'skins/aurorawx/weather-icons/svg/wi-earthquake.svg',
    'skins/aurorawx/weather-icons/svg/wi-fahrenheit.svg',
    'skins/aurorawx/weather-icons/svg/wi-fire.svg',
    'skins/aurorawx/weather-icons/svg/wi-flood.svg',
    'skins/aurorawx/weather-icons/svg/wi-fog.svg',
    'skins/aurorawx/weather-icons/svg/wi-gale-warning.svg',
    'skins/aurorawx/weather-icons/svg/wi-hail.svg',
    'skins/aurorawx/weather-icons/svg/wi-horizon-alt.svg',
    'skins/aurorawx/weather-icons/svg/wi-horizon.svg',
    'skins/aurorawx/weather-icons/svg/wi-hot.svg',
    'skins/aurorawx/weather-icons/svg/wi-humidity.svg',
    'skins/aurorawx/weather-icons/svg/wi-hurricane-warning.svg',
    'skins/aurorawx/weather-icons/svg/wi-hurricane.svg',
    'skins/aurorawx/weather-icons/svg/wi-lightning.svg',
    'skins/aurorawx/weather-icons/svg/wi-lunar-eclipse.svg',
    'skins/aurorawx/weather-icons/svg/wi-meteor.svg',
    'skins/aurorawx/weather-icons/svg/wi-moon-alt-first-quarter.svg',
    'skins/aurorawx/weather-icons/svg/wi-moon-alt-full.svg',
    'skins/aurorawx/weather-icons/svg/wi-moon-alt-new.svg',
    'skins/aurorawx/weather-icons/svg/wi-moon-alt-third-quarter.svg',
    'skins/aurorawx/weather-icons/svg/wi-moon-alt-waning-crescent-1.svg',
    'skins/aurorawx/weather-icons/svg/wi-moon-alt-waning-crescent-2.svg',
    'skins/aurorawx/weather-icons/svg/wi-moon-alt-waning-crescent-3.svg',
    'skins/aurorawx/weather-icons/svg/wi-moon-alt-waning-crescent-4.svg',
    'skins/aurorawx/weather-icons/svg/wi-moon-alt-waning-crescent-5.svg',
    'skins/aurorawx/weather-icons/svg/wi-moon-alt-waning-crescent-6.svg',
    'skins/aurorawx/weather-icons/svg/wi-moon-alt-waning-gibbous-1.svg',
    'skins/aurorawx/weather-icons/svg/wi-moon-alt-waning-gibbous-2.svg',
    'skins/aurorawx/weather-icons/svg/wi-moon-alt-waning-gibbous-3.svg',
    'skins/aurorawx/weather-icons/svg/wi-moon-alt-waning-gibbous-4.svg',
    'skins/aurorawx/weather-icons/svg/wi-moon-alt-waning-gibbous-5.svg',
    'skins/aurorawx/weather-icons/svg/wi-moon-alt-waning-gibbous-6.svg',
    'skins/aurorawx/weather-icons/svg/wi-moon-alt-waxing-crescent-1.svg',
    'skins/aurorawx/weather-icons/svg/wi-moon-alt-waxing-crescent-2.svg',
    'skins/aurorawx/weather-icons/svg/wi-moon-alt-waxing-crescent-3.svg',
    'skins/aurorawx/weather-icons/svg/wi-moon-alt-waxing-crescent-4.svg',
    'skins/aurorawx/weather-icons/svg/wi-moon-alt-waxing-crescent-5.svg',
    'skins/aurorawx/weather-icons/svg/wi-moon-alt-waxing-crescent-6 .svg',
    'skins/aurorawx/weather-icons/svg/wi-moon-alt-waxing-gibbous-1.svg',
    'skins/aurorawx/weather-icons/svg/wi-moon-alt-waxing-gibbous-2.svg',
    'skins/aurorawx/weather-icons/svg/wi-moon-alt-waxing-gibbous-3.svg',
    'skins/aurorawx/weather-icons/svg/wi-moon-alt-waxing-gibbous-4.svg',
    'skins/aurorawx/weather-icons/svg/wi-moon-alt-waxing-gibbous-5.svg',
    'skins/aurorawx/weather-icons/svg/wi-moon-alt-waxing-gibbous-6 .svg',
    'skins/aurorawx/weather-icons/svg/wi-moon-first-quarter.svg',
    'skins/aurorawx/weather-icons/svg/wi-moon-full.svg',
    'skins/aurorawx/weather-icons/svg/wi-moon-new.svg',
    'skins/aurorawx/weather-icons/svg/wi-moon-third-quarter.svg',
    'skins/aurorawx/weather-icons/svg/wi-moon-waning-crescent-1.svg',
    'skins/aurorawx/weather-icons/svg/wi-moon-waning-crescent-2.svg',
    'skins/aurorawx/weather-icons/svg/wi-moon-waning-crescent-3.svg',
    'skins/aurorawx/weather-icons/svg/wi-moon-waning-crescent-4 .svg',
    'skins/aurorawx/weather-icons/svg/wi-moon-waning-crescent-5.svg',
    'skins/aurorawx/weather-icons/svg/wi-moon-waning-crescent-6.svg',
    'skins/aurorawx/weather-icons/svg/wi-moon-waning-gibbous-1.svg',
    'skins/aurorawx/weather-icons/svg/wi-moon-waning-gibbous-2.svg',
    'skins/aurorawx/weather-icons/svg/wi-moon-waning-gibbous-3.svg',
    'skins/aurorawx/weather-icons/svg/wi-moon-waning-gibbous-4.svg',
    'skins/aurorawx/weather-icons/svg/wi-moon-waning-gibbous-5 .svg',
    'skins/aurorawx/weather-icons/svg/wi-moon-waning-gibbous-6.svg',
    'skins/aurorawx/weather-icons/svg/wi-moon-waxing-crescent-1.svg',
    'skins/aurorawx/weather-icons/svg/wi-moon-waxing-crescent-2.svg',
    'skins/aurorawx/weather-icons/svg/wi-moon-waxing-crescent-3.svg',
    'skins/aurorawx/weather-icons/svg/wi-moon-waxing-crescent-4.svg',
    'skins/aurorawx/weather-icons/svg/wi-moon-waxing-crescent-5.svg',
    'skins/aurorawx/weather-icons/svg/wi-moon-waxing-crescent-6 .svg',
    'skins/aurorawx/weather-icons/svg/wi-moon-waxing-gibbous-1.svg',
    'skins/aurorawx/weather-icons/svg/wi-moon-waxing-gibbous-2.svg',
    'skins/aurorawx/weather-icons/svg/wi-moon-waxing-gibbous-3.svg',
    'skins/aurorawx/weather-icons/svg/wi-moon-waxing-gibbous-4 .svg',
    'skins/aurorawx/weather-icons/svg/wi-moon-waxing-gibbous-5.svg',
    'skins/aurorawx/weather-icons/svg/wi-moon-waxing-gibbous-6.svg',
    'skins/aurorawx/weather-icons/svg/wi-moonrise.svg',
    'skins/aurorawx/weather-icons/svg/wi-moonset.svg',
    'skins/aurorawx/weather-icons/svg/wi-na.svg',
    'skins/aurorawx/weather-icons/svg/wi-night-alt-cloudy-gusts.svg',
    'skins/aurorawx/weather-icons/svg/wi-night-alt-cloudy-high.svg',
    'skins/aurorawx/weather-icons/svg/wi-night-alt-cloudy-windy.svg',
    'skins/aurorawx/weather-icons/svg/wi-night-alt-cloudy.svg',
    'skins/aurorawx/weather-icons/svg/wi-night-alt-hail.svg',
    'skins/aurorawx/weather-icons/svg/wi-night-alt-lightning.svg',
    'skins/aurorawx/weather-icons/svg/wi-night-alt-partly-cloudy.svg',
    'skins/aurorawx/weather-icons/svg/wi-night-alt-rain-mix.svg',
    'skins/aurorawx/weather-icons/svg/wi-night-alt-rain-wind.svg',
    'skins/aurorawx/weather-icons/svg/wi-night-alt-rain.svg',
    'skins/aurorawx/weather-icons/svg/wi-night-alt-showers.svg',
    'skins/aurorawx/weather-icons/svg/wi-night-alt-sleet-storm.svg',
    'skins/aurorawx/weather-icons/svg/wi-night-alt-sleet.svg',
    'skins/aurorawx/weather-icons/svg/wi-night-alt-snow-thunderstorm.svg',
    'skins/aurorawx/weather-icons/svg/wi-night-alt-snow-wind.svg',
    'skins/aurorawx/weather-icons/svg/wi-night-alt-snow.svg',
    'skins/aurorawx/weather-icons/svg/wi-night-alt-sprinkle.svg',
    'skins/aurorawx/weather-icons/svg/wi-night-alt-storm-showers.svg',
    'skins/aurorawx/weather-icons/svg/wi-night-alt-thunderstorm.svg',
    'skins/aurorawx/weather-icons/svg/wi-night-clear.svg',
    'skins/aurorawx/weather-icons/svg/wi-night-cloudy-gusts.svg',
    'skins/aurorawx/weather-icons/svg/wi-night-cloudy-high.svg',
    'skins/aurorawx/weather-icons/svg/wi-night-cloudy-windy.svg',
    'skins/aurorawx/weather-icons/svg/wi-night-cloudy.svg',
    'skins/aurorawx/weather-icons/svg/wi-night-fog.svg',
    'skins/aurorawx/weather-icons/svg/wi-night-hail.svg',
    'skins/aurorawx/weather-icons/svg/wi-night-lightning.svg',
    'skins/aurorawx/weather-icons/svg/wi-night-partly-cloudy.svg',
    'skins/aurorawx/weather-icons/svg/wi-night-rain-mix.svg',
    'skins/aurorawx/weather-icons/svg/wi-night-rain-wind.svg',
    'skins/aurorawx/weather-icons/svg/wi-night-rain.svg',
    'skins/aurorawx/weather-icons/svg/wi-night-showers.svg',
    'skins/aurorawx/weather-icons/svg/wi-night-sleet-storm.svg',
    'skins/aurorawx/weather-icons/svg/wi-night-sleet.svg',
    'skins/aurorawx/weather-icons/svg/wi-night-snow-thunderstorm.svg',
    'skins/aurorawx/weather-icons/svg/wi-night-snow-wind.svg',
    'skins/aurorawx/weather-icons/svg/wi-night-snow.svg',
    'skins/aurorawx/weather-icons/svg/wi-night-sprinkle.svg',
    'skins/aurorawx/weather-icons/svg/wi-night-storm-showers.svg',
    'skins/aurorawx/weather-icons/svg/wi-night-thunderstorm.svg',
    'skins/aurorawx/weather-icons/svg/wi-rain-mix.svg',
    'skins/aurorawx/weather-icons/svg/wi-rain-wind.svg',
    'skins/aurorawx/weather-icons/svg/wi-rain.svg',
    'skins/aurorawx/weather-icons/svg/wi-raindrop.svg',
    'skins/aurorawx/weather-icons/svg/wi-raindrops.svg',
    'skins/aurorawx/weather-icons/svg/wi-refresh-alt.svg',
    'skins/aurorawx/weather-icons/svg/wi-refresh.svg',
    'skins/aurorawx/weather-icons/svg/wi-sandstorm.svg',
    'skins/aurorawx/weather-icons/svg/wi-showers.svg',
    'skins/aurorawx/weather-icons/svg/wi-sleet.svg',
    'skins/aurorawx/weather-icons/svg/wi-small-craft-advisory.svg',
    'skins/aurorawx/weather-icons/svg/wi-smog.svg',
    'skins/aurorawx/weather-icons/svg/wi-smoke.svg',
    'skins/aurorawx/weather-icons/svg/wi-snow-wind.svg',
    'skins/aurorawx/weather-icons/svg/wi-snow.svg',
    'skins/aurorawx/weather-icons/svg/wi-snowflake-cold.svg',
    'skins/aurorawx/weather-icons/svg/wi-solar-eclipse.svg',
    'skins/aurorawx/weather-icons/svg/wi-sprinkle.svg',
    'skins/aurorawx/weather-icons/svg/wi-stars.svg',
    'skins/aurorawx/weather-icons/svg/wi-storm-showers.svg',
    'skins/aurorawx/weather-icons/svg/wi-storm-warning.svg',
    'skins/aurorawx/weather-icons/svg/wi-strong-wind.svg',
    'skins/aurorawx/weather-icons/svg/wi-sunrise.svg',
    'skins/aurorawx/weather-icons/svg/wi-sunset.svg',
    'skins/aurorawx/weather-icons/svg/wi-thermometer-exterior.svg',
    'skins/aurorawx/weather-icons/svg/wi-thermometer-internal.svg',
    'skins/aurorawx/weather-icons/svg/wi-thermometer.svg',
    'skins/aurorawx/weather-icons/svg/wi-thunderstorm.svg',
    'skins/aurorawx/weather-icons/svg/wi-time-1.svg',
    'skins/aurorawx/weather-icons/svg/wi-time-10.svg',
    'skins/aurorawx/weather-icons/svg/wi-time-11.svg',
    'skins/aurorawx/weather-icons/svg/wi-time-12.svg',
    'skins/aurorawx/weather-icons/svg/wi-time-2.svg',
    'skins/aurorawx/weather-icons/svg/wi-time-3.svg',
    'skins/aurorawx/weather-icons/svg/wi-time-4.svg',
    'skins/aurorawx/weather-icons/svg/wi-time-5.svg',
    'skins/aurorawx/weather-icons/svg/wi-time-6.svg',
    'skins/aurorawx/weather-icons/svg/wi-time-7.svg',
    'skins/aurorawx/weather-icons/svg/wi-time-8.svg',
    'skins/aurorawx/weather-icons/svg/wi-time-9.svg',
    'skins/aurorawx/weather-icons/svg/wi-tornado.svg',
    'skins/aurorawx/weather-icons/svg/wi-train.svg',
    'skins/aurorawx/weather-icons/svg/wi-tsunami.svg',
    'skins/aurorawx/weather-icons/svg/wi-umbrella.svg',
    'skins/aurorawx/weather-icons/svg/wi-volcano.svg',
    'skins/aurorawx/weather-icons/svg/wi-wind-beaufort-0.svg',
    'skins/aurorawx/weather-icons/svg/wi-wind-beaufort-1.svg',
    'skins/aurorawx/weather-icons/svg/wi-wind-beaufort-10.svg',
    'skins/aurorawx/weather-icons/svg/wi-wind-beaufort-11.svg',
    'skins/aurorawx/weather-icons/svg/wi-wind-beaufort-12.svg',
    'skins/aurorawx/weather-icons/svg/wi-wind-beaufort-2.svg',
    'skins/aurorawx/weather-icons/svg/wi-wind-beaufort-3.svg',
    'skins/aurorawx/weather-icons/svg/wi-wind-beaufort-4.svg',
    'skins/aurorawx/weather-icons/svg/wi-wind-beaufort-5.svg',
    'skins/aurorawx/weather-icons/svg/wi-wind-beaufort-6.svg',
    'skins/aurorawx/weather-icons/svg/wi-wind-beaufort-7.svg',
    'skins/aurorawx/weather-icons/svg/wi-wind-beaufort-8.svg',
    'skins/aurorawx/weather-icons/svg/wi-wind-beaufort-9.svg',
    'skins/aurorawx/weather-icons/svg/wi-wind-deg.svg',
    'skins/aurorawx/weather-icons/svg/wi-windy.svg',
    'skins/aurorawx/week.html.tmpl',
    'skins/aurorawx/year-%Y.html.tmpl',
    'skins/aurorawx/year.html.tmpl',
    'skins/aurorawx/yesterday.html.tmpl',
]
# --- END GENERATED SKIN FILES ---


def loader():
    return AuroraWXInstaller()


class AuroraWXInstaller(ExtensionInstaller):

    def __init__(self):
        payload = {
            "version": VERSION,
            "name": "aurorawx",
            "description": "Material-design weather + aurora skin for WeeWX 5.x"
                           " (NeoWX Material fork with camera timelapses and"
                           " live space weather).",
            "author": "Greg",
            "author_email": "",
            "config": {
                "StdReport": {
                    "AuroraWXReport": {"skin": "aurorawx", "enable": "true"},
                },
            },
            "files": [
                ("bin/user", [
                    "bin/user/aurorawx/__init__.py",
                    "bin/user/aurorawx/scanner.py",
                    "bin/user/aurorawx/searchlist.py",
                ]),
                ("skins/aurorawx", SKIN_FILES),
            ],
        }
        super(AuroraWXInstaller, self).__init__(payload)
        # WeeWX 5's ExtensionInstaller is a plain dict subclass and never sets
        # instance attributes; mirror the file list so ``installer.files`` works.
        self.files = payload["files"]
